server:
  port: 8082
spring:
  application:
    name: api-gateway
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG
      org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"



#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://eureka-service/eureka-service/eureka
#eureka.client.service-url.defaultZone=http://eureka-service/eureka-service/eureka/
#eureka.client.service-url.defaultZone=http://eureka-service:80/eureka-service/
#eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
#
#eureka.client.enabled=true
#eureka.client.service-url.defaultZone=http://eureka-service:8761/
#
#
#
#
#
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

