apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    app: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: media-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: spring.mvc.servlet.path
              value: /media-service
            - name: DATASOURCE_HOST
              value: 192.168.55.75
            - name: SPRING_RABBITMQ_HOST
              value: 192.168.55.75
          volumeMounts:
            - name: shared-images
              mountPath: /images

        - name: thumbnail-sidecar
          image: thumbnail-sidecar:local
          ports:
            - containerPort: 9090


      volumes:
        - name: shared-images
          emptyDir: {}
