apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
    - name: sidecar-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: app-port
      protocol: TCP
      port: 8086
      targetPort: 8086

