apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.49
          ports:
            - containerPort: 16686 # Web UI
            - containerPort: 14250 # Collector gRPC
            - containerPort: 14268 # Collector HTTP (для otel-collector)
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
  ports:
    - name: collector-grpc
      port: 14250
      targetPort: 14250
    - name: collector-http
      port: 14268
      targetPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
spec:
  selector:
    app: jaeger
  ports:
    - name: query
      port: 16686
      targetPort: 16686
      nodePort: 30086
  type: NodePort
