apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: sidecar-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: app-port
      protocol: TCP
      port: 8088
      targetPort: 8088