apiVersion: apps/v1
kind: Deployment
metadata:
  name: trek-service
  labels:
    app: trek-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trek-service
  template:
    metadata:
      labels:
        app: trek-service
    spec:
      containers:
        - name: trek-service
          image: trek-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: spring.mvc.servlet.path
              value: /trek-service
            - name: DATASOURCE_HOST
#              value: 192.168.1.101
              value: 192.168.227.75
            - name: SPRING_RABBITMQ_HOST
#              value: 192.168.1.101
              value: 192.168.227.75
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"