apiVersion: v1
kind: Service
metadata:
  name: trek-service
spec:
  type: NodePort
  selector:
    app: trek-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32001
