version: '3'
services:
  greentrail-db-user-api:
    image: postgres:12
    restart: always
    ports:
      - 5441:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: greentrail-db-media