spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5442/greentrail-db-chat
    #url: jdbc:postgresql://localhost:5445/user-api
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
  application:
    name: chat-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /chat-service/v3/api-docs/swagger-config
    url: /chat-service/v3/api-docs



server:
  port: 8087

eureka:
  client:
    enabled: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    #      defaultZone: http://eureka-server:8761/eureka/
#    registry-fetch-interval-seconds: 5
#    initial-instance-info-replication-interval-seconds: 5
#    register-with-eureka: true
#    fetch-registry: true
#  server:
#    enable-self-preservation: false
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true