apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        # Основний сервіс
        - name: user-service
          image: user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: spring.mvc.servlet.path
              value: /user-service
            - name: DATASOURCE_HOST
              value: 192.168.227.75
            - name: SPRING_RABBITMQ_HOST
              value: 192.168.227.75
          volumeMounts:
            # Маунтимо директорію для логів
            - name: logs
              mountPath: /var/log/user-service

        # Fluent Bit сайдкар
        - name: fluent-bit-sidecar
          image: logging-sidecar:local
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /var/log/user-service

      volumes:
        - name: logs
          emptyDir: {}
