apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: spring.mvc.servlet.path
              value: /user-service
            - name: DATASOURCE_HOST
#              value: 192.168.1.101
              value: 10.137.234.75
            - name: SPRING_RABBITMQ_HOST
#              value: 192.168.1.101
              value: 10.137.234.75